### ISSUE TITLE
in main.yml, line 36, persistent: "{{ item.persistent }}"

### ISSUE THREAD

**Issue by gitkeystone** [buluma/ansible-role-selinux#41]
# Describe the bug
persistent: "{{ item.persistent }}"
if the `item` has no attribute of `persistent`, the ansible will output a error.

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- hosts: all
  become: yes

  vars:
    # bootstrap
    bootstrap_user: root
    bootstrap_wait_for_host: yes

    # selinux
    selinux_state: enforcing 
    selinux_reboot: true
    selinux_booleans:
      - name: httpd_can_network_connect
      - name: abrt_anon_write
        state: false
        persistent: false

  roles:
    - buluma.bootstrap
    - buluma.selinux
```

## Output

TASK [buluma.selinux : Manage selinux booleans] ************************************************************************************************
fatal: [192.168.10.5]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'persistent'. 'dict object' has no attribute 'persistent'\n\nThe error appears to be in '/root/ansible-for-devops/communal/roles/buluma.selinux/tasks/main.yml': line 32, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Manage selinux booleans\n      ^ here\n"}

## Environment
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)
